# Generated by Django 4.0.2 on 2022-03-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbook',
            old_name='time_period',
            new_name='date_return',
        ),
    ]
