# Generated by Django 4.2.5 on 2023-10-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'CUSTOMER'), (1, 'ADMIN')], default=1, max_length=50),
        ),
    ]
