# Generated by Django 4.0.2 on 2022-03-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_time_period_issuedbook_date_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STUDENT'), (1, 'ADMIN')], default=1, max_length=50),
        ),
    ]
