# Generated by Django 4.0.2 on 2022-03-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecategory_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=13)),
                ('Volume', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('issued_date', models.DateField(auto_now=True)),
                ('book_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('roll_no', models.CharField(blank=True, max_length=3)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(upload_to='uploads/profile-pic/')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePageCategory',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STUDENT')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
