# Generated by Django 4.0.2 on 2022-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_issuedbook_student_delete_homepagecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
