# Generated by Django 4.0.2 on 2022-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_requestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='button_value',
            field=models.BooleanField(default=False),
        ),
    ]
