# Generated by Django 4.0.2 on 2022-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_maincategory_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STUDENT'), (1, 'ADMIN')], default=1, max_length=50),
        ),
    ]
