# Generated by Django 4.0.2 on 2022-03-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_requestbook_button_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestbook_name', to='home.book'),
        ),
    ]
