# Generated by Django 4.0.2 on 2022-03-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bookcategory_parent_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bookcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STUDENT'), (1, 'ADMIN')], default=1, max_length=50),
        ),
    ]
