# Generated by Django 4.0.2 on 2022-03-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_maincategory_parent_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='main_category',
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.bookcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bookcategory'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
