# Generated by Django 4.0.2 on 2022-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookprice',
        ),
        migrations.AddField(
            model_name='student',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_email_verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'STUDENT'), (1, 'ADMIN')], default=1, max_length=50),
        ),
        migrations.DeleteModel(
            name='BookPrice',
        ),
    ]
