# Generated by Django 4.0.2 on 2022-03-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_book_bookprice_student_email_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='Volume',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='sub_category',
        ),
    ]
