# Generated by Django 4.0.2 on 2022-03-08 12:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_issuedbook_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=home.models.expiry),
        ),
    ]
