# Generated by Django 4.2.5 on 2023-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_book_category_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_email_verfied',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STUDENT')], default=1, max_length=50),
        ),
    ]
